#ifndef _RCC_VERSION_H
#define _RCC_VERSION_H 1

#define RCC_VERSION_MAJOR 4
#define RCC_VERSION_MINOR 0
#define RCC_VERSION_PATCH 0
#define RCC_VERSION_NUMBER 400000
#define RCC_VERSION_STRING "4.0.0"




#define ROOKCC_VERSION_MAJOR RCC_VERSION_MAJOR
#define ROOKCC_VERSION_MINOR RCC_VERSION_MINOR
#define ROOKCC_VERSION_PATCH RCC_VERSION_PATCH
#define ROOKCC_VERSION_NUMBER RCC_VERSION_NUMBER
#define ROOKCC_VERSION_STRING RCC_VERSION_STRING

#endif
