complete -c rcc -s o -r -d 'write output file'
complete -c rcc -s E -d 'preprocess only'
complete -c rcc -s S -d 'emit machine code listing'
complete -c rcc -s c -d 'emit relocatable object'
complete -c rcc -o run -d 'compile and run a native executable'
complete -c rcc -o static -d 'emit an interpreter free executable'
complete -c rcc -o fPIC -d 'emit pic code with -c'
complete -c rcc -s g -d 'emit dwarf 4 debug data'
complete -c rcc -l check -d 'parse verify and optimize only'
complete -c rcc -l emit-ir -d 'emit verified ir'
complete -c rcc -l emit-tokens -d 'emit lexer tokens'
complete -c rcc -l target -r -a 'x86_64 aarch64 riscv64' -d 'select target'
complete -c rcc -l sysroot -r -d 'select target sysroot'
complete -c rcc -l resource-dir -r -d 'select resource tree'
complete -c rcc -l print-targets -d 'list targets'
complete -c rcc -l print-target-info -d 'describe selected target'
complete -c rcc -l print-backends -d 'list native backends'
complete -c rcc -l print-toolchain -d 'show compiler registries'
complete -c rcc -l print-optimizations -d 'show optimization catalog'
complete -c rcc -l print-conformance -d 'show conformance catalog'
complete -c rcc -l print-builtins -d 'show builtin catalog'
complete -c rcc -s h -l help -d 'show help'
complete -c rcc -l version -d 'show version'
complete -c rookcc -w rcc
